# Generated by Django 5.1.7 on 2025-03-19 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=12, unique=True)),
                ('data_nascimento', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('telefone', models.CharField(max_length=15)),
                ('cep', models.CharField(max_length=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.curso')),
            ],
        ),
    ]
