# Generated by Django 5.1.7 on 2025-03-26 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='matricula',
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=12)),
                ('periodo', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno'), ('I', 'Integral')], default='M', max_length=1)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.estudante', verbose_name='Estudante')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.curso', verbose_name='Curso')),
            ],
        ),
    ]
